server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.atguigu.cloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
    
spring:
  application:
    name: atguigu-scms-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud_db_two
    username: root
    password: 123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 2000

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/